name: Запрос на статью 📝
description: Предложите тему для следующей статьи в блоге!
title: "[Тема]: "
labels: ["запрос на статью"] 

body:
  - type: markdown
    attributes:
      value: "Спасибо, что предлагаете тему для статьи! Пожалуйста, заполните форму ниже, чтобы помочь нам лучше понять вашу идею."

  - type: input
    id: topic
    attributes:
      label: "📌 Краткое название темы"
      description: "Опишите тему статьи в нескольких словах"
      placeholder: "Пример: Использование Temporal в .NET"

  - type: textarea
    id: description
    attributes:
      label: "📖 Описание темы"
      description: "Расскажите, что именно вас интересует в этой теме. Например, какие проблемы хотите решить, какие технологии должны быть освещены и т. д."
      placeholder: "Меня интересует, как правильно работать с Temporal в .NET: создание workflows, обработка ошибок, масштабирование..."
    validations:
      required: true

  - type: dropdown
    id: expertise_level
    attributes:
      label: "🎯 Уровень сложности"
      description: "На какой уровень аудитории должна быть рассчитана статья?"
      options:
        - "Начальный (для новичков)"
        - "Средний (для разработчиков с опытом)"
        - "Продвинутый (для архитекторов и senior-разработчиков)"
      default: 1

  - type: textarea
    id: why_important
    attributes:
      label: "💡 Почему эта тема важна?"
      description: "Опишите, почему эта тема актуальна и как она может помочь сообществу."
      placeholder: "Temporal становится популярным решением для workflow orchestration, но примеров для .NET мало. Разбор best practices поможет разработчикам."

  - type: checkboxes
    id: notifications
    attributes:
      label: "🔔 Хотите быть уведомлены о публикации статьи?"
      options:
        - label: "Да, отметьте меня в комментарии, когда статья будет опубликована!"
          required: false
